#
# Executes commands at login pre-zshrc.

#
# Editors
#

# export EDITOR='vim'
# export VISUAL='view'
export PAGER='less'

#
# Paths
#

# Ensure path arrays do not contain duplicates.
# typeset -gU cdpath fpath mailpath path
typeset -gU cdpath fpath mailpath

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
# path=(
#     /usr/local/{bin,sbin}
#     $path
# )

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
# export LESS='-F -g -i -M -R -S -w -X -z-4'
export LESS='-g -i -M -R -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
# if (( $#commands[(i)lesspipe(|.sh)] )); then
#     export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
# fi

#
# Temporary Files
#

# export TMPDIR="/tmp/$LOGNAME"
# if [[ ! -d "$TMPDIR" ]]; then
#     mkdir -p -m 700 "$TMPDIR"
# fi
#
# TMPPREFIX="${TMPDIR%/}/zsh"

# if [[ -d "/run/systemd/seats/" ]] && [[ -x "$(command -v systemctl)" ]]; then
#     sd_out=$(systemctl --user show-environment)
#     sd_env=(${(f)sd_out})
#     for var in "${sd_env[@]}"; do
#         IFS="=" read key value <<<"$var"
#         if [[ ! -v $key ]]; then
#             export $var
#         fi
#     done
#     unset sd_out sd_env
# fi
