# Move configurations to .config dirs
export ZDOTDIR=~/.config/zsh

# Prepend ~/bin
typeset -U PATH path
path=( ~/bin ~/.local/bin $path )

if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR}/zprofile" ]]; then
  source "${ZDOTDIR}/zprofile"
fi
